export enum ActionLabels {
  "TOGGLE_MQTT_CONNECTION_MODAL",
  "MQTT_CONNECTED",
  "RECEIVED_MQTT_MESSAGE",
  "TOGGLE_SELECT_FROM_REALTIME_LIST",
  "DESELECT_FROM_REALTIME_LIST",
  // BLOCK CODING
  "ADD_CODE_BLOCK",
  "DELETE_CODE_BLOCK",
  "UPDATE_CODE_BLOCK_VALUES",
}
